#!/usr/bin/env bash
#
# Establish a target project's delivery projection and commit it.
#
# This is the GUK BPM pilot's single mutating task, and it is deliberately the
# smallest useful mutation there is: it adds one generated file that the
# dashboard already knows how to read. Additive, reversible, and immediately
# visible — which is what a first pilot on a live project should be.
#
# The fence is verified immediately before this runs and advanced immediately
# after, so the branch-movement guard is exercised by a commit that actually
# happens rather than by a simulation of one.
#
# It writes exactly one path: delivery/PROJECT-STATE.yml. Nothing else in the
# target is touched, and the run spec's authorised paths are what contain it.

set -euo pipefail

STATE_DIR="${GC_UNATTENDED_STATE_DIR:?the runner supplies this}"
RUN_ID="${GC_UNATTENDED_RUN_ID:?the runner supplies this}"
REPO="$(git rev-parse --show-toplevel)"
OUT="$REPO/delivery/PROJECT-STATE.yml"

# The projector is the producer; this script only places what it produced. The
# runner publishes the projection into the state directory as the run proceeds,
# so the authoritative document already exists by the time this task runs.
SRC="$STATE_DIR/PROJECT-STATE.yml"
if [ ! -f "$SRC" ]; then
  echo "no projection at $SRC — the run has not published one, so there is nothing to establish" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
cp -f "$SRC" "$OUT"
git add "$OUT"

if git diff --cached --quiet; then
  echo "the delivery projection is unchanged; nothing to commit"
  exit 0
fi

git commit -q -F - <<COMMIT
chore(delivery): establish the delivery projection the dashboard reads

Generated by the Gas City delivery projector during run ${RUN_ID}. It is a
projection of that run's own durable journal, not a hand-written document, and
it is overwritten by each subsequent run — so it is not a place to record
anything by hand.

This is the pilot's only mutation of this repository.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>
COMMIT

echo "committed $(git rev-parse HEAD)"
