#!/usr/bin/env bash
#
# Install the run's delivery projection into the target repository and commit it.
#
# The collision logic is not here. It lives in Go, in
# internal/unattended/projectionpublish.go, where it is covered by the regression
# suite the GUK BPM pilot's central finding earned — a shell script that decides
# whether it may overwrite a governance document is a shell script nobody can
# test properly. This is the thin part: call the publisher, then commit what it
# produced.
#
# Usage: publish-projection.sh <repo-relative-target-path>
#
# The target is a parameter because projects differ. A project with no governance
# layer may want the projection at delivery/PROJECT-STATE.yml; GUK BPM already
# keeps a hand-maintained record there and needs the projection somewhere of its
# own. Baking either choice in would make the engine wrong for the other kind.

set -euo pipefail

TARGET="${1:?usage: publish-projection.sh <repo-relative-target-path>}"
STATE_DIR="${GC_UNATTENDED_STATE_DIR:?the runner supplies this}"
RUN_ID="${GC_UNATTENDED_RUN_ID:?the runner supplies this}"
PUBLISHER="${GC_UNATTENDED_BIN:-/var/tmp/unattended-run}"
REPO="$(git rev-parse --show-toplevel)"

"$PUBLISHER" publish -state "$STATE_DIR" -repo "$REPO" -target "$TARGET"

git add "$TARGET"
if git diff --cached --quiet -- "$TARGET"; then
  echo "the delivery projection is unchanged; nothing to commit"
  exit 0
fi

# Identity is supplied per-invocation rather than written into the repository.
#
# The GUK BPM pilot found the reason. A linked worktree shares .git/config with
# every other worktree of that repository — forty-one of them there — so setting
# user.email to make one commit work would change shared state the run was never
# authorised to touch. Passing it with -c affects exactly this command.
git \
  -c "user.name=${GIT_AUTHOR_NAME:-corsolv}" \
  -c "user.email=${GIT_AUTHOR_EMAIL:-support@corsolv.com}" \
  commit -q -F - <<COMMIT
chore(delivery): publish the Gas City execution projection

Generated by the Gas City delivery projector during run ${RUN_ID}, at
${TARGET}. It is a projection of that run's durable journal and is overwritten
by each subsequent run, so it is not a place to record anything by hand.

This file carries execution facts only. The project's own governance record —
current phase, planned work, governance decisions — remains the authority for
those, and this projector refuses to write over it.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>
COMMIT

echo "committed $(git rev-parse HEAD)"
