#!/usr/bin/env bash
#
# Establish a target project's delivery projection and commit it.
#
# This is the GUK BPM pilot's single mutating task, and it is deliberately the
# smallest useful mutation there is: it adds one generated file that the
# dashboard already knows how to read. Additive, reversible, and immediately
# visible — which is what a first pilot on a live project should be.
#
# The fence is verified immediately before this runs and advanced immediately
# after, so the branch-movement guard is exercised by a commit that actually
# happens rather than by a simulation of one.
#
# It writes exactly one path: delivery/PROJECT-STATE.yml. Nothing else in the
# target is touched, and the run spec's authorised paths are what contain it.

set -euo pipefail

STATE_DIR="${GC_UNATTENDED_STATE_DIR:?the runner supplies this}"
RUN_ID="${GC_UNATTENDED_RUN_ID:?the runner supplies this}"
REPO="$(git rev-parse --show-toplevel)"
OUT="$REPO/delivery/PROJECT-STATE.yml"

# The projector is the producer; this script only places what it produced. The
# runner publishes the projection into the state directory as the run proceeds,
# so the authoritative document already exists by the time this task runs.
SRC="$STATE_DIR/PROJECT-STATE.yml"
if [ ! -f "$SRC" ]; then
  echo "no projection at $SRC — the run has not published one, so there is nothing to establish" >&2
  exit 1
fi

# Refuse to clobber a file this producer did not author.
#
# The GUK BPM pilot found this the hard way. The approval described establishing
# delivery/PROJECT-STATE.yml as additive — the file was genuinely absent at the
# commit the assessment read — but by execution time the project's own
# origin/main carried a hand-maintained canonical active-state record at exactly
# that path, whose header says a human or a new session must be able to determine
# current phase from THIS FILE. Overwriting it with a run-scoped projection would
# have destroyed a governance document and replaced it with something untruthful
# about the project, inside a path the run was technically authorised to write.
#
# An authorised path is not the same as an authorised act. The generated marker
# below is what distinguishes a file this producer owns from one it would be
# taking, and a file with no marker is a human decision, not a merge conflict.
MARKER="# generated-by: gas-city-delivery-projector"

if [ -e "$OUT" ] && ! head -20 "$OUT" | grep -qF "$MARKER"; then
  {
    echo "REFUSING TO PUBLISH: $OUT already exists and was not written by this projector."
    echo
    echo "It carries no '$MARKER' marker, so it belongs to the project rather than"
    echo "to this run. Overwriting it would replace a document the project maintains"
    echo "with a projection of a single run — a destructive act inside an authorised"
    echo "path. That is a human decision and this run is not entitled to make it."
    echo
    echo "First lines of the existing file:"
    head -5 "$OUT" | sed 's/^/    /'
    echo
    echo "To proceed, a person must either choose a different publish path for the"
    echo "Gas City projection, or explicitly accept replacing the project's record."
  } >&2
  exit 65 # EX_DATAERR — the target is not what the run was told it would be
fi

mkdir -p "$(dirname "$OUT")"
{
  echo "$MARKER"
  echo "# run: ${RUN_ID}"
  cat "$SRC"
} > "$OUT"
git add "$OUT"

if git diff --cached --quiet; then
  echo "the delivery projection is unchanged; nothing to commit"
  exit 0
fi

# Identity is supplied per-invocation rather than written into the repository.
#
# The GUK BPM pilot found the reason. A linked worktree shares .git/config with
# every other worktree of that repository — forty-one of them there — so setting
# user.email to make one commit work would change shared state the run was never
# authorised to touch. Passing it with -c affects exactly this command.
#
# The default is the identity this programme already commits under; an operator
# who wants a different one sets the standard git environment variables.
git \
  -c "user.name=${GIT_AUTHOR_NAME:-corsolv}" \
  -c "user.email=${GIT_AUTHOR_EMAIL:-support@corsolv.com}" \
  commit -q -F - <<COMMIT
chore(delivery): establish the delivery projection the dashboard reads

Generated by the Gas City delivery projector during run ${RUN_ID}. It is a
projection of that run's own durable journal, not a hand-written document, and
it is overwritten by each subsequent run — so it is not a place to record
anything by hand.

This is the pilot's only mutation of this repository.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>
COMMIT

echo "committed $(git rev-parse HEAD)"
